---
services:
  valo-spectra-server:
    image: kichi128/spectra-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
      - "5101:5101"
      - "5200:5200"
    volumes:
      - ./keys:/app/keys
    environment:
      - INSECURE=true
    platform: linux/amd64
